plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - [TBD]"

dependencies {
    api "org.eclipse.collections:eclipse-collections-api:13.0.0"
    api "org.eclipse.collections:eclipse-collections:13.0.0"
    api "com.carrotsearch:hppc:0.11.1"
    api "org.pcollections:pcollections:5.0.0"
}
