plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - Format"

dependencies {
    api platform("org.apache.tika:tika-bom:4.0.0")

    api "com.opencsv:opencsv:5.12.0"

    api "org.apache.thrift:libthrift:0.24.0"

    api "com.vladsch.flexmark:flexmark-all:0.64.8"
}
