dependencies {
    implementation platform("org.springframework.ai:spring-ai-bom:2.0.1")

    // implementation platform("dev.langchain4j:langchain4j-bom:1.4.0")
    // implementation platform("dev.langchain4j:langchain4j-community-bom:1.4.0-beta10")

    // implementation platform("org.bsc.langgraph4j:langgraph4j-bom:1.6.2")

    implementation platform("ai.timefold.solver:timefold-solver-bom:2.6.0-rc-1")

    implementation platform("org.kie:bom:10.2.0")

    implementation platform("org.drools:drools-bom:10.2.0")

    implementation platform("com.embabel.agent:embabel-agent-dependencies:1.5.1")

    constraints {
        implementation "net.sourceforge.tess4j:tess4j:5.20.0"

        implementation "edu.stanford.nlp:stanford-corenlp:4.5.10"

        implementation "org.apache.opennlp:opennlp:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-cli:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-dl:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-dl-gpu:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-ml-libsvm:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-ml-perceptron:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-ml-bayes:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-ml-maxent:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-ml-commons:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-ml:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-core:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-api:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-model-resolver:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-runtime:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-distr:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-docs:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-morfologik:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-uima:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-tools:3.0.0-M5"
        implementation "org.apache.opennlp:opennlp-models:3.0.0-M1"
        implementation "org.apache.opennlp:opennlp-tools-models:2.5.8"
        implementation "org.apache.opennlp:opennlp-morfologik-addon:2.5.8"

        implementation "io.jenetics:jpx:4.0.0"
        implementation "io.jenetics:jenetics:9.0.0"
        implementation "io.jenetics:jenetics.ext:9.0.0"
        implementation "io.jenetics:jenetics.prog:9.0.0"
        implementation "io.jenetics:jenetics.xml:9.0.0"
        implementation "io.jenetics:facilejdbc:2.1.1"
        implementation "io.jenetics:lattices:3.0.0.ALPHA4"
        implementation "io.jenetics:colt:2.0.0"
        implementation "io.jenetics:prngine:2.0.0"

        implementation "org.:action:1.31"
        implementation "org.tweetyproject:agents:1.31"
        implementation "org.tweetyproject:comparator:1.31"
        implementation "org.tweetyproject.agents:dialogues:1.31"
        implementation "org.tweetyproject.arg:aba:1.31"
        implementation "org.tweetyproject.arg:adf:1.31"
        implementation "org.tweetyproject.arg:bipolar:1.31"
        implementation "org.tweetyproject.arg:aspic:1.31"
        implementation "org.tweetyproject.arg:deductive:1.31"
        implementation "org.tweetyproject.arg:delp:1.31"
        implementation "org.tweetyproject.arg:dung:1.31"
        implementation "org.tweetyproject.arg:lp:1.31"
        implementation "org.tweetyproject.arg:prob:1.31"
        implementation "org.tweetyproject.arg:saf:1.31"
        implementation "org.tweetyproject.arg:setaf:1.31"
        implementation "org.tweetyproject.arg:social:1.31"
        implementation "org.tweetyproject.arg:rankings:1.31"
        implementation "org.tweetyproject:beliefdynamics:1.31"
        implementation "org.tweetyproject:cli:1.31"
        implementation "org.tweetyproject:commons:1.31"
        implementation "org.tweetyproject:graphs:1.31"
        implementation "org.tweetyproject.logics:bpm:1.31"
        implementation "org.tweetyproject.logics:cl:1.31"
        implementation "org.tweetyproject.logics:commons:1.31"
        implementation "org.tweetyproject.logics:dl:1.31"
        implementation "org.tweetyproject.logics:fol:1.31"
        implementation "org.tweetyproject.logics:ml:1.31"
        implementation "org.tweetyproject.logics:mln:1.31"
        implementation "org.tweetyproject.logics:petri:1.31"
        implementation "org.tweetyproject.logics:pcl:1.31"
        implementation "org.tweetyproject.logics:pl:1.31"
        implementation "org.tweetyproject.logics:qbf:1.31"
        implementation "org.tweetyproject.logics:rcl:1.31"
        implementation "org.tweetyproject.logics:rdl:1.31"
        implementation "org.tweetyproject.logics:rpcl:1.31"
        implementation "org.tweetyproject.logics:translators:1.31"
        implementation "org.tweetyproject.lp:asp:1.31"
        implementation "org.tweetyproject.lp.asp:beliefdynamics:1.31"
        implementation "org.tweetyproject.lp:nlp:1.31"
        implementation "org.tweetyproject:machinelearning:1.31"
        implementation "org.tweetyproject:math:1.31"
        implementation "org.tweetyproject:plugin:1.31"
        implementation "org.tweetyproject:preferences:1.31"
        implementation "org.tweetyproject:web:1.31"
        implementation "org.tweetyproject:sat:1.31"
        implementation "org.tweetyproject.arg:weighted:1.31"
        implementation "org.tweetyproject.arg:caf:1.31"
        implementation "org.tweetyproject.arg:eaf:1.31"
        implementation "org.tweetyproject:causal:1.31"
        implementation "org.tweetyproject.arg:explanations:1.31"()
        implementation "org.tweetyproject:tweety-full:1.31"
        //

        // implementation("org.eclipse.lmos:arc-azure-client:$arcVersion")
        // implementation("org.eclipse.lmos:arc-spring-boot-starter:$arcVersion")
        // implementation("org.eclipse.lmos:arc-reader-pdf:$arcVersion")
        // implementation("org.eclipse.lmos:arc-reader-html:$arcVersion")
        // implementation("org.eclipse.lmos:arc-assistants:$arcVersion")
        // implementation("org.eclipse.lmos:arc-reader-html:$arcVersion")
        // implementation("org.eclipse.lmos:arc-api:$arcVersion")
        // implementation("org.eclipse.lmos:arc-graphql-spring-boot-starter:$arcVersion")
    }
}
