repositories {
    maven {
        url = "https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/"
    }

    dependencies {
        constraints {
            implementation "org.apache.pdfbox:pdfbox:3.0.8"

            implementation "org.apache.poi:poi:5.5.1"
            implementation "org.apache.poi:poi-ooxml:5.5.1"

            implementation "org.jfree:jfreechart:1.5.6"

            implementation "net.sf.jasperreports:jasperreports-chrome:7.0.1"
            implementation "net.sf.jasperreports:jasperreports-google-maps:7.0.1"
            implementation "net.sf.jasperreports:jasperreports-interactivity:7.0.1"
            implementation "net.sf.jasperreports:jasperreports-sort:7.0.1"
            implementation "net.sf.jasperreports:jasperreports-velocity:7.0.1"

            implementation "net.sf.jasperreports:jasperreports:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-functions:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-chart-themes:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-chart-customizers:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-annotation-processors:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-metadata:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-xalan:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-servlets-j2ee:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-servlets:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-olap:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-jdt:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-jaxen:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-javascript:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-hibernate-j2ee:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-hibernate:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-groovy:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-pdf:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-functions:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-fastexcel:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-excel-poi:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-ejbql-j2ee:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-ejbql:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-chart-themes:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-spring:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-chart-customizers:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-charts:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-castor:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-data-adapters-http:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-data-adapters:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-json:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-barcode4j:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-barbecue:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-ant:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-javaflow:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-fonts:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-annotation-processors:7.0.8"
            implementation "net.sf.jasperreports:jasperreports-metadata:7.0.8"

            implementation "org.eclipse.birt:org.eclipse.birt.core.script.function:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.chart.device.pdf:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.sampledb:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.dataextraction:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.odp:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.docx:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.html:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.docx:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.data:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.xml:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.data.oda.pojo:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.chart.examples.core:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.chart.device.svg:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.prototype.excel:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.data.oda.mongodb:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.core:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.excel:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.dataextraction.csv:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.ppt:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.ods:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.html:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.pptx:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.ppt:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.item.crosstab.core:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.fonts:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.data:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.script.javascript:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.ooxml:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.model:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.pptx:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.odt:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.pdf:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.jdbc:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.model.adapter.oda:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.chart.device.extension:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.odf:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.wpml:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.postscript:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.pdf:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.odt:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.jdbc.dbprofile.sampledb:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.chart.reportitem:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.adapter:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.data.aggregation:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.hive:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.bidi.utils:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.jdbc.dbprofile:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.chart.engine.extension:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.wpml:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.postscript:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.odp:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.engine.emitter.config.ods:4.24.0"
            implementation "org.eclipse.birt:org.eclipse.birt.report.data.oda.jdbc.dbprofile.sampledb:4.24.0"
        }
    }
}
