dependencies {
    implementation "org.infinispan:infinispan-bom:16.2.2"
    implementation "org.apache.ignite:ignite-bom:2.18.0"

    constraints {
        implementation "javax.cache:cache-api:1.1.1"

        implementation "com.github.ben-manes.caffeine:caffeine:3.2.4"
        implementation "com.github.ben-manes.caffeine:jcache:3.2.4"
    }
}
