plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM"

dependencies {
    api platform(project(":mifos-conventions-gradle-base-bom-ai"))
    api project(":mifos-conventions-gradle-base-bom-amazon")
    api project(":mifos-conventions-gradle-base-bom-auth")
    api project(":mifos-conventions-gradle-base-bom-automation")
    api project(":mifos-conventions-gradle-base-bom-cache")
    api project(":mifos-conventions-gradle-base-bom-camel")
    api project(":mifos-conventions-gradle-base-bom-cep")
    api project(":mifos-conventions-gradle-base-bom-check")
    api project(":mifos-conventions-gradle-base-bom-cli")
    api project(":mifos-conventions-gradle-base-bom-cloudevents")
    api project(":mifos-conventions-gradle-base-bom-collections")
    api project(":mifos-conventions-gradle-base-bom-commons")
    api project(":mifos-conventions-gradle-base-bom-cryptography")
    api project(":mifos-conventions-gradle-base-bom-data")
    api project(":mifos-conventions-gradle-base-bom-finance")
    api project(":mifos-conventions-gradle-base-bom-format")
    api project(":mifos-conventions-gradle-base-bom-geo")
    api project(":mifos-conventions-gradle-base-bom-google")
    api project(":mifos-conventions-gradle-base-bom-graphic")
    api project(":mifos-conventions-gradle-base-bom-i18n")
    api project(":mifos-conventions-gradle-base-bom-jakarta")
    api project(":mifos-conventions-gradle-base-bom-json")
    api project(":mifos-conventions-gradle-base-bom-kubernetes")
    api project(":mifos-conventions-gradle-base-bom-lock")
    api project(":mifos-conventions-gradle-base-bom-logging")
    api project(":mifos-conventions-gradle-base-bom-manifold")
    api project(":mifos-conventions-gradle-base-bom-mapping")
    api project(":mifos-conventions-gradle-base-bom-math")
    api project(":mifos-conventions-gradle-base-bom-measure")
    api project(":mifos-conventions-gradle-base-bom-net")
    api project(":mifos-conventions-gradle-base-bom-observability")
    api project(":mifos-conventions-gradle-base-bom-performance")
    api project(":mifos-conventions-gradle-base-bom-reporting")
    api project(":mifos-conventions-gradle-base-bom-sdk")
    api project(":mifos-conventions-gradle-base-bom-spring")
    api project(":mifos-conventions-gradle-base-bom-template")
    api project(":mifos-conventions-gradle-base-bom-test")
    api project(":mifos-conventions-gradle-base-bom-util")
    api project(":mifos-conventions-gradle-base-bom-vaadin")
    api project(":mifos-conventions-gradle-base-bom-validation")
    api project(":mifos-conventions-gradle-base-bom-web")
    api project(":mifos-conventions-gradle-base-bom-workflow")
    api project(":mifos-conventions-gradle-base-bom-xml")
}
