plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - [TBD]"

configurations.all {
    exclude module: "slf4j-jdk14"
}

dependencies {
    api platform("org.slf4j:slf4j-bom:2.0.18")

    // api platform("org.apache.logging.log4j:log4j-bom:2.25.3")

    api "ch.qos.logback:logback-core:1.6.2"
    api "ch.qos.logback:logback-classic:1.6.2"

    api "org.jboss.logging:jboss-logging:3.6.3.Final"
}
