pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral().content {
            excludeModule("javax.media", "jai_core")
        }
        gradlePluginPortal()
        maven {
            url = uri("https://mifos.jfrog.io/artifactory/mifosx-gradle-local")
        }
    }
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral().content {
            excludeModule("javax.media", "jai_core")
        }
        maven {
            url = uri("https://mifos.jfrog.io/artifactory/mifosx-gradle-local")
        }
        gradlePluginPortal()
    }

    configurations.configureEach {
        resolutionStrategy {
            dependencySubstitution {
                substitute module( "com.burgstaller:okhttp-digest:1.10" ) using module("io.github.rburgst:okhttp-digest:1.21") because "okhttp-digest only version 1.21 is available on Maven Central. Old version was on jcenter, which asciidoctor-gradle-plugin depends on transitively through simplified-jruby-gradle-plugin via http-builder-ng-okhttp "
            }
        }
    }
    dependencies {
        classpath "io.freefair.aggregate-javadoc:io.freefair.aggregate-javadoc.gradle.plugin:9.5.0"
        classpath "com.palantir.java-format-idea:com.palantir.java-format-idea.gradle.plugin:2.97.0"
        classpath "com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.61.0"
        classpath "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin:3.18.0"
        classpath "pl.allegro.tech.build.axion-release:pl.allegro.tech.build.axion-release.gradle.plugin:1.21.3"
    }
}

rootProject.name = "mifos-conventions-gradle-base"

include(":mifos-conventions-gradle-base-core")
project(":mifos-conventions-gradle-base-core").projectDir = file("${rootDir}/modules/gradle/base/core")
include(":mifos-conventions-gradle-base-doc")
project(":mifos-conventions-gradle-base-doc").projectDir = file("${rootDir}/modules/gradle/base/doc")
include(":mifos-conventions-gradle-base-dependencies")
project(":mifos-conventions-gradle-base-dependencies").projectDir = file("${rootDir}/modules/gradle/base/dependencies")
include(":mifos-conventions-gradle-base-bom-ai")
project(":mifos-conventions-gradle-base-bom-ai").projectDir = file("${rootDir}/modules/gradle/base/bom/ai")
include(":mifos-conventions-gradle-base-bom-amazon")
project(":mifos-conventions-gradle-base-bom-amazon").projectDir = file("${rootDir}/modules/gradle/base/bom/amazon")
include(":mifos-conventions-gradle-base-bom-auth")
project(":mifos-conventions-gradle-base-bom-auth").projectDir = file("${rootDir}/modules/gradle/base/bom/auth")
include(":mifos-conventions-gradle-base-bom-automation")
project(":mifos-conventions-gradle-base-bom-automation").projectDir = file("${rootDir}/modules/gradle/base/bom/automation")
include(":mifos-conventions-gradle-base-bom-cache")
project(":mifos-conventions-gradle-base-bom-cache").projectDir = file("${rootDir}/modules/gradle/base/bom/cache")
include(":mifos-conventions-gradle-base-bom-camel")
project(":mifos-conventions-gradle-base-bom-camel").projectDir = file("${rootDir}/modules/gradle/base/bom/camel")
include(":mifos-conventions-gradle-base-bom-cep")
project(":mifos-conventions-gradle-base-bom-cep").projectDir = file("${rootDir}/modules/gradle/base/bom/cep")
include(":mifos-conventions-gradle-base-bom-check")
project(":mifos-conventions-gradle-base-bom-check").projectDir = file("${rootDir}/modules/gradle/base/bom/check")
include(":mifos-conventions-gradle-base-bom-cli")
project(":mifos-conventions-gradle-base-bom-cli").projectDir = file("${rootDir}/modules/gradle/base/bom/cli")
include(":mifos-conventions-gradle-base-bom-cloudevents")
project(":mifos-conventions-gradle-base-bom-cloudevents").projectDir = file("${rootDir}/modules/gradle/base/bom/cloudevents")
include(":mifos-conventions-gradle-base-bom-collections")
project(":mifos-conventions-gradle-base-bom-collections").projectDir = file("${rootDir}/modules/gradle/base/bom/collections")
include(":mifos-conventions-gradle-base-bom-commons")
project(":mifos-conventions-gradle-base-bom-commons").projectDir = file("${rootDir}/modules/gradle/base/bom/commons")
include(":mifos-conventions-gradle-base-bom-cryptography")
project(":mifos-conventions-gradle-base-bom-cryptography").projectDir = file("${rootDir}/modules/gradle/base/bom/cryptography")
include(":mifos-conventions-gradle-base-bom-data")
project(":mifos-conventions-gradle-base-bom-data").projectDir = file("${rootDir}/modules/gradle/base/bom/data")
include(":mifos-conventions-gradle-base-bom-finance")
project(":mifos-conventions-gradle-base-bom-finance").projectDir = file("${rootDir}/modules/gradle/base/bom/finance")
include(":mifos-conventions-gradle-base-bom-format")
project(":mifos-conventions-gradle-base-bom-format").projectDir = file("${rootDir}/modules/gradle/base/bom/format")
include(":mifos-conventions-gradle-base-bom-google")
project(":mifos-conventions-gradle-base-bom-google").projectDir = file("${rootDir}/modules/gradle/base/bom/google")
include(":mifos-conventions-gradle-base-bom-graphic")
project(":mifos-conventions-gradle-base-bom-graphic").projectDir = file("${rootDir}/modules/gradle/base/bom/graphic")
include(":mifos-conventions-gradle-base-bom-i18n")
project(":mifos-conventions-gradle-base-bom-i18n").projectDir = file("${rootDir}/modules/gradle/base/bom/i18n")
include(":mifos-conventions-gradle-base-bom-jakarta")
project(":mifos-conventions-gradle-base-bom-jakarta").projectDir = file("${rootDir}/modules/gradle/base/bom/jakarta")
include(":mifos-conventions-gradle-base-bom-json")
project(":mifos-conventions-gradle-base-bom-json").projectDir = file("${rootDir}/modules/gradle/base/bom/json")
include(":mifos-conventions-gradle-base-bom-kubernetes")
project(":mifos-conventions-gradle-base-bom-kubernetes").projectDir = file("${rootDir}/modules/gradle/base/bom/kubernetes")
include(":mifos-conventions-gradle-base-bom-lock")
project(":mifos-conventions-gradle-base-bom-lock").projectDir = file("${rootDir}/modules/gradle/base/bom/lock")
include(":mifos-conventions-gradle-base-bom-logging")
project(":mifos-conventions-gradle-base-bom-logging").projectDir = file("${rootDir}/modules/gradle/base/bom/logging")
include(":mifos-conventions-gradle-base-bom-manifold")
project(":mifos-conventions-gradle-base-bom-manifold").projectDir = file("${rootDir}/modules/gradle/base/bom/manifold")
include(":mifos-conventions-gradle-base-bom-mapping")
project(":mifos-conventions-gradle-base-bom-mapping").projectDir = file("${rootDir}/modules/gradle/base/bom/mapping")
include(":mifos-conventions-gradle-base-bom-math")
project(":mifos-conventions-gradle-base-bom-math").projectDir = file("${rootDir}/modules/gradle/base/bom/math")
include(":mifos-conventions-gradle-base-bom-measure")
project(":mifos-conventions-gradle-base-bom-measure").projectDir = file("${rootDir}/modules/gradle/base/bom/measure")
include(":mifos-conventions-gradle-base-bom-net")
project(":mifos-conventions-gradle-base-bom-net").projectDir = file("${rootDir}/modules/gradle/base/bom/net")
include(":mifos-conventions-gradle-base-bom-geo")
project(":mifos-conventions-gradle-base-bom-geo").projectDir = file("${rootDir}/modules/gradle/base/bom/geo")
include(":mifos-conventions-gradle-base-bom-spring")
project(":mifos-conventions-gradle-base-bom-spring").projectDir = file("${rootDir}/modules/gradle/base/bom/spring")
include(":mifos-conventions-gradle-base-bom-workflow")
project(":mifos-conventions-gradle-base-bom-workflow").projectDir = file("${rootDir}/modules/gradle/base/bom/workflow")
include(":mifos-conventions-gradle-base-bom-performance")
project(":mifos-conventions-gradle-base-bom-performance").projectDir = file("${rootDir}/modules/gradle/base/bom/performance")
include(":mifos-conventions-gradle-base-bom-observability")
project(":mifos-conventions-gradle-base-bom-observability").projectDir = file("${rootDir}/modules/gradle/base/bom/observability")
include(":mifos-conventions-gradle-base-bom-reporting")
project(":mifos-conventions-gradle-base-bom-reporting").projectDir = file("${rootDir}/modules/gradle/base/bom/reporting")
include(":mifos-conventions-gradle-base-bom-sdk")
project(":mifos-conventions-gradle-base-bom-sdk").projectDir = file("${rootDir}/modules/gradle/base/bom/sdk")
include(":mifos-conventions-gradle-base-bom-template")
project(":mifos-conventions-gradle-base-bom-template").projectDir = file("${rootDir}/modules/gradle/base/bom/template")
include(":mifos-conventions-gradle-base-bom-test")
project(":mifos-conventions-gradle-base-bom-test").projectDir = file("${rootDir}/modules/gradle/base/bom/test")
include(":mifos-conventions-gradle-base-bom-util")
project(":mifos-conventions-gradle-base-bom-util").projectDir = file("${rootDir}/modules/gradle/base/bom/util")
include(":mifos-conventions-gradle-base-bom-vaadin")
project(":mifos-conventions-gradle-base-bom-vaadin").projectDir = file("${rootDir}/modules/gradle/base/bom/vaadin")
include(":mifos-conventions-gradle-base-bom-validation")
project(":mifos-conventions-gradle-base-bom-validation").projectDir = file("${rootDir}/modules/gradle/base/bom/validation")
include(":mifos-conventions-gradle-base-bom-web")
project(":mifos-conventions-gradle-base-bom-web").projectDir = file("${rootDir}/modules/gradle/base/bom/web")
include(":mifos-conventions-gradle-base-bom-xml")
project(":mifos-conventions-gradle-base-bom-xml").projectDir = file("${rootDir}/modules/gradle/base/bom/xml")
include(":mifos-conventions-gradle-base-bom")
project(":mifos-conventions-gradle-base-bom").projectDir = file("${rootDir}/modules/gradle/base/bom/all")
include(":mifos-conventions-gradle-base-java")
project(":mifos-conventions-gradle-base-java").projectDir = file("${rootDir}/modules/gradle/base/java")
include(":mifos-conventions-gradle-base-plugin")
project(":mifos-conventions-gradle-base-plugin").projectDir = file("${rootDir}/modules/gradle/base/plugin")
include(":mifos-conventions-gradle-base-template")
project(":mifos-conventions-gradle-base-template").projectDir = file("${rootDir}/modules/gradle/base/template")
