plugins {
    id "org.mifos.conventions.gradle.internal.plugin"
}

description = "Mifos Initiative - Conventions - Gradle - Base - Core"

group = "org.mifos.conventions"

gradlePlugin {
    plugins {
        MifosGradleBaseLayoutPlugin {
            id = "org.mifos.conventions.gradle.base.layout"
            implementationClass = "org.mifos.conventions.gradle.base.core.MifosGradleBaseLayoutPlugin"
        }
    }
}

dependencies {
    implementation libs.commons.io
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}