plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - [TBD]"

dependencies {
    api "org.infinispan:infinispan-bom:16.2.2"
    api "org.apache.ignite:ignite-bom:2.18.0"

    api "javax.cache:cache-api:1.1.1"
    api "com.github.ben-manes.caffeine:caffeine:3.2.4"
    api "com.github.ben-manes.caffeine:jcache:3.2.4"
}
