plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - Command Line"

dependencies {
    api platform("dev.tamboui:tamboui-bom:0.4.0")

    // api platform("org.apache.maven.resolver:maven-resolver:2.0.21")
    api platform("org.apache.maven.resolver:maven-resolver:1.9.27")

    api platform("org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-bom:3.3.7")

    // api "org.apache.maven:maven-resolver-provider:4.0.0-rc-6"
    api "org.apache.maven:maven-resolver-provider:3.9.16"
    api "org.apache.maven:plexus-utils:4.0.0-alpha-5"

    api "info.picocli:picocli:4.7.7"
    api "info.picocli:picocli-codegen:4.7.7"
    api "info.picocli:picocli-spring-boot-starter:4.7.7"
    api "info.picocli:picocli-shell-jline2:4.7.7"
    api "info.picocli:picocli-shell-jline3:4.7.7"
    api "info.picocli:picocli-groovy:4.7.7"

    api "org.jline:jline:4.3.1"
    api "org.jline:jline-terminal-ffm:4.3.1"
    api "org.jline:jline-terminal-jni:4.3.1"
    api "org.jline:jline-terminal-jna:4.3.1"
    api "org.jline:jline-reader:4.3.1"
    api "org.jline:jline-builtins:4.3.1"
    api "org.jline:jline-console:4.3.1"
    api "org.jline:jline-terminal-jansi:3.30.16"
    api "org.jline:jline-curses:3.30.16"
    api "org.jline:jline-shell:4.3.1"
    api "org.jline:jline-console-ui:4.3.1"
    api "org.jline:jline-graal:4.3.1"
    api "org.jline:jline-picocli:4.3.1"
    api "org.jline:jline-prompt:4.3.1"
    api "org.jline:jline-native:4.3.1"
    api "org.jline:jline-remote-ssh:4.3.1"
    api "org.jline:jline-remote-telnet:4.3.1"
    api "org.jline:jansi-core:4.3.1"
    api "org.jline:jline-style:4.3.1"
    api "org.jline:jline-terminal:4.3.1"
    api "org.jline:jline-groovy:4.3.1"

    api "io.github.crramirez:casciian:1.6.0"
    api "io.github.crramirez:casciian-terminal-component:1.6.0"
    api "io.github.crramirez:casciian-java-desktop:1.6.0"
    api "io.github.crramirez:casciian-spring-boot-starter:1.1.0"

    api "org.apache.ant:ant:1.10.17"
}
