plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - [TBD]"

dependencies {
    api "com.microsoft.playwright:playwright:1.62.0"
    api "com.microsoft.playwright:driver-bundle:1.62.0"
    api "com.microsoft.playwright:driver:1.62.0"
}
