plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - Amazon"

dependencies {
    api platform("software.amazon.awssdk:bom:2.54.7")

    api "software.amazon.awssdk.crt:aws-crt:0.48.4"
    api "software.amazon.awssdk.crt:aws-crt-android:0.48.4"
}
