plugins {
    id "org.mifos.conventions.gradle.internal.bom"
}

description = "Mifos Initiative - Conventions - Gradle - Base - BOM - Net"

dependencies {
    api platform("io.netty:netty-bom:4.2.17.Final")

    api platform("com.linecorp.armeria:armeria-bom:1.41.0")

    api platform("io.grpc:grpc-bom:1.83.1")
    api platform("com.google.protobuf:protobuf-bom:4.36.0")

    api "io.netty:netty-tcnative:2.0.81.Final"
    api "io.netty:netty-tcnative-classes:2.0.81.Final"
    api "io.netty:netty-tcnative-boringssl-static:2.0.81.Final"

    api "com.salesforce.servicelibs:reactive-grpc-common:1.2.4"
    api "com.salesforce.servicelibs:reactor-grpc:1.2.4"
    api "com.salesforce.servicelibs:reactor-grpc-stub:1.2.4"
    api "com.salesforce.servicelibs:reactor-grpc-retry:1.2.4"

    api "com.beanit:asn1bean:1.16.0"
    api "com.beanit:asn1bean-compiler:1.16.0"
}
